export type RootStackParamList = {
  landing: undefined;
  terms: undefined;
  login: undefined;
  signup: undefined;
  verifyemail: undefined;
  setup: { userId: string };
  setup2: { userId: string };
  setup3: { userId: string };
  forgotpassword: undefined;
  about: undefined;
  discovery: { userId?: string } | undefined;
  likes: { userId?: string } | undefined;
  messages: { userId?: string } | undefined;
  profile: { userId?: string } | undefined;
  settings: { userId?: string } | undefined;
  viewprofile: { userId?: string } | undefined;
  bannedlist: { userId?: string } | undefined;
  communityguidelines: { userId?: string } | undefined;
  reportaccount: { userId?: string } | undefined;
  editprofile: { userId?: string } | undefined;
};
